# Generated by Django 4.2.9 on 2024-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_remove_project_images_image_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
