# Generated by Django 4.2.9 on 2024-02-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects_app",
            "0002_projects_alter_image_image_delete_fundraisecampaign_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="project",
        ),
        migrations.AddField(
            model_name="projects",
            name="pictures",
            field=models.ManyToManyField(to="projects_app.image"),
        ),
    ]
