# Generated by Django 4.2.9 on 2024-02-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0003_remove_image_project_projects_pictures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="pictures",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="tags",
        ),
    ]
