# Generated by Django 4.2.9 on 2024-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0004_remove_projects_pictures_remove_projects_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="pictures",
            field=models.ManyToManyField(to="projects_app.image"),
        ),
        migrations.AddField(
            model_name="projects",
            name="tags",
            field=models.ManyToManyField(to="projects_app.tag"),
        ),
    ]
