# Generated by Django 4.2.9 on 2024-02-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0005_projects_pictures_projects_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="pictures",
        ),
        migrations.AddField(
            model_name="image",
            name="projectrel1",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects_app.projects",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="images",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="tag",
            name="projectrel2",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects_app.projects",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="project_images/"),
        ),
        migrations.RemoveField(
            model_name="projects",
            name="tags",
        ),
        migrations.AddField(
            model_name="projects",
            name="tags",
            field=models.CharField(blank=True),
        ),
    ]
