# Generated by Django 4.2.9 on 2024-02-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0006_remove_projects_pictures_image_projectrel1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="images",
        ),
        migrations.AlterField(
            model_name="image",
            name="projectrel1",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_images",
                to="projects_app.projects",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="tags",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
