# Generated by Django 4.2.9 on 2024-02-15 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects_app",
            "0007_remove_projects_images_alter_image_projectrel1_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="projectrel1",
        ),
        migrations.AddField(
            model_name="image",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects_app.projects",
            ),
        ),
    ]
