# Generated by Django 4.2.9 on 2024-02-15 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0008_remove_image_projectrel1_image_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="project",
            new_name="projectrel1",
        ),
    ]
