# Generated by Django 4.2.9 on 2024-02-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0009_rename_project_image_projectrel1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="projectrel1",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="projectrel2",
            new_name="project",
        ),
    ]
