# Generated by Django 4.2.9 on 2024-02-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0010_rename_projectrel1_image_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="tags",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
