# Generated by Django 4.2.9 on 2024-02-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0011_alter_projects_tags_delete_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="tags",
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
