# Generated by Django 4.2.9 on 2024-02-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0012_alter_projects_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="tags",
            field=models.CharField(blank=True),
        ),
    ]
