# Generated by Django 4.2.9 on 2024-02-11 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Country', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faceBookAccount',
            field=models.URLField(default='https://example.com', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='012xxxxxxxx', max_length=100, null=True),
        ),
    ]
