# Generated by Django 4.2.9 on 2024-02-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_alter_profile_birthdate_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Country', max_length=100, null=True),
        ),
    ]
