# Generated by Django 4.2.9 on 2024-02-11 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_remove_profile_birthdate_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='faceBookAccount',
            field=models.URLField(default='https://example.com', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='012xxxxxxxx', max_length=100, null=True),
        ),
    ]
