# Generated by Django 4.2.9 on 2024-02-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth_app", "0005_profile_birthdate_profile_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
