# Generated by Django 4.2.9 on 2024-02-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
