# Generated by Django 4.2.10 on 2024-02-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField()),
                ('userID', models.CharField()),
                ('commentContent', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField()),
                ('userID', models.CharField()),
                ('startDate', models.DateField()),
                ('projectName', models.CharField()),
                ('projectCategory', models.CharField()),
                ('projectTarget', models.FloatField()),
                ('endDate', models.DateField()),
                ('currentFunds', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField()),
            ],
        ),
    ]
