# Generated by Django 4.2.10 on 2024-02-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userID',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='userID',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectID',
        ),
    ]
