# Generated by Django 4.2.10 on 2024-02-17 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_rename_userid_comment_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
