# Generated by Django 4.2.10 on 2024-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_comment_commentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
