# Generated by Django 4.2.10 on 2024-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_report_comment_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField()),
                ('username', models.CharField()),
                ('donationAmount', models.FloatField()),
            ],
        ),
    ]
