# Generated by Django 4.2.10 on 2024-02-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.CharField()),
                ('username', models.CharField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Report',
            new_name='CommentReport',
        ),
        migrations.AlterField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='currentFunds',
            field=models.FloatField(default=0),
        ),
    ]
