# Generated by Django 4.2.10 on 2024-02-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_projectreport_rename_report_commentreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.CharField()),
                ('username', models.CharField()),
                ('ratingValue', models.IntegerField()),
            ],
        ),
    ]
