# Generated by Django 4.2.10 on 2024-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField()),
                ('tagContent', models.CharField()),
            ],
        ),
    ]
