# Generated by Django 4.2.10 on 2024-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
